// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package com.middleware.order.proto;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.middleware.order.proto.OrderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 productId = 1;</code>
     */
    int getProductId();

    /**
     * <code>string productName = 2;</code>
     */
    java.lang.String getProductName();
    /**
     * <code>string productName = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>string productColor = 3;</code>
     */
    java.lang.String getProductColor();
    /**
     * <code>string productColor = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductColorBytes();

    /**
     * <code>string productDescription = 4;</code>
     */
    java.lang.String getProductDescription();
    /**
     * <code>string productDescription = 4;</code>
     */
    com.google.protobuf.ByteString
        getProductDescriptionBytes();

    /**
     * <code>double productPrice = 5;</code>
     */
    double getProductPrice();
  }
  /**
   * Protobuf type {@code com.middleware.order.proto.OrderRequest}
   */
  public  static final class OrderRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.middleware.order.proto.OrderRequest)
      OrderRequestOrBuilder {
    // Use OrderRequest.newBuilder() to construct.
    private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderRequest() {
      productId_ = 0;
      productName_ = "";
      productColor_ = "";
      productDescription_ = "";
      productPrice_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              productId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              productColor_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              productDescription_ = s;
              break;
            }
            case 41: {

              productPrice_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.middleware.order.proto.Order.OrderRequest.class, com.middleware.order.proto.Order.OrderRequest.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private int productId_;
    /**
     * <code>int32 productId = 1;</code>
     */
    public int getProductId() {
      return productId_;
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object productName_;
    /**
     * <code>string productName = 2;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      }
    }
    /**
     * <code>string productName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTCOLOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object productColor_;
    /**
     * <code>string productColor = 3;</code>
     */
    public java.lang.String getProductColor() {
      java.lang.Object ref = productColor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productColor_ = s;
        return s;
      }
    }
    /**
     * <code>string productColor = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductColorBytes() {
      java.lang.Object ref = productColor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTDESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object productDescription_;
    /**
     * <code>string productDescription = 4;</code>
     */
    public java.lang.String getProductDescription() {
      java.lang.Object ref = productDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string productDescription = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductDescriptionBytes() {
      java.lang.Object ref = productDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTPRICE_FIELD_NUMBER = 5;
    private double productPrice_;
    /**
     * <code>double productPrice = 5;</code>
     */
    public double getProductPrice() {
      return productPrice_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0) {
        output.writeInt32(1, productId_);
      }
      if (!getProductNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName_);
      }
      if (!getProductColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productColor_);
      }
      if (!getProductDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productDescription_);
      }
      if (productPrice_ != 0D) {
        output.writeDouble(5, productPrice_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, productId_);
      }
      if (!getProductNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName_);
      }
      if (!getProductColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productColor_);
      }
      if (!getProductDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productDescription_);
      }
      if (productPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, productPrice_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.middleware.order.proto.Order.OrderRequest)) {
        return super.equals(obj);
      }
      com.middleware.order.proto.Order.OrderRequest other = (com.middleware.order.proto.Order.OrderRequest) obj;

      boolean result = true;
      result = result && (getProductId()
          == other.getProductId());
      result = result && getProductName()
          .equals(other.getProductName());
      result = result && getProductColor()
          .equals(other.getProductColor());
      result = result && getProductDescription()
          .equals(other.getProductDescription());
      result = result && (
          java.lang.Double.doubleToLongBits(getProductPrice())
          == java.lang.Double.doubleToLongBits(
              other.getProductPrice()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId();
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductName().hashCode();
      hash = (37 * hash) + PRODUCTCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getProductColor().hashCode();
      hash = (37 * hash) + PRODUCTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getProductDescription().hashCode();
      hash = (37 * hash) + PRODUCTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProductPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.middleware.order.proto.Order.OrderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.middleware.order.proto.OrderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.middleware.order.proto.OrderRequest)
        com.middleware.order.proto.Order.OrderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.middleware.order.proto.Order.OrderRequest.class, com.middleware.order.proto.Order.OrderRequest.Builder.class);
      }

      // Construct using com.middleware.order.proto.Order.OrderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        productId_ = 0;

        productName_ = "";

        productColor_ = "";

        productDescription_ = "";

        productPrice_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderRequest_descriptor;
      }

      public com.middleware.order.proto.Order.OrderRequest getDefaultInstanceForType() {
        return com.middleware.order.proto.Order.OrderRequest.getDefaultInstance();
      }

      public com.middleware.order.proto.Order.OrderRequest build() {
        com.middleware.order.proto.Order.OrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.middleware.order.proto.Order.OrderRequest buildPartial() {
        com.middleware.order.proto.Order.OrderRequest result = new com.middleware.order.proto.Order.OrderRequest(this);
        result.productId_ = productId_;
        result.productName_ = productName_;
        result.productColor_ = productColor_;
        result.productDescription_ = productDescription_;
        result.productPrice_ = productPrice_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.middleware.order.proto.Order.OrderRequest) {
          return mergeFrom((com.middleware.order.proto.Order.OrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.middleware.order.proto.Order.OrderRequest other) {
        if (other == com.middleware.order.proto.Order.OrderRequest.getDefaultInstance()) return this;
        if (other.getProductId() != 0) {
          setProductId(other.getProductId());
        }
        if (!other.getProductName().isEmpty()) {
          productName_ = other.productName_;
          onChanged();
        }
        if (!other.getProductColor().isEmpty()) {
          productColor_ = other.productColor_;
          onChanged();
        }
        if (!other.getProductDescription().isEmpty()) {
          productDescription_ = other.productDescription_;
          onChanged();
        }
        if (other.getProductPrice() != 0D) {
          setProductPrice(other.getProductPrice());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.middleware.order.proto.Order.OrderRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.middleware.order.proto.Order.OrderRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int productId_ ;
      /**
       * <code>int32 productId = 1;</code>
       */
      public int getProductId() {
        return productId_;
      }
      /**
       * <code>int32 productId = 1;</code>
       */
      public Builder setProductId(int value) {
        
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productId = 1;</code>
       */
      public Builder clearProductId() {
        
        productId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productName_ = "";
      /**
       * <code>string productName = 2;</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder clearProductName() {
        
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productColor_ = "";
      /**
       * <code>string productColor = 3;</code>
       */
      public java.lang.String getProductColor() {
        java.lang.Object ref = productColor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productColor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productColor = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductColorBytes() {
        java.lang.Object ref = productColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productColor = 3;</code>
       */
      public Builder setProductColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productColor = 3;</code>
       */
      public Builder clearProductColor() {
        
        productColor_ = getDefaultInstance().getProductColor();
        onChanged();
        return this;
      }
      /**
       * <code>string productColor = 3;</code>
       */
      public Builder setProductColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productColor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productDescription_ = "";
      /**
       * <code>string productDescription = 4;</code>
       */
      public java.lang.String getProductDescription() {
        java.lang.Object ref = productDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productDescription = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProductDescriptionBytes() {
        java.lang.Object ref = productDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productDescription = 4;</code>
       */
      public Builder setProductDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productDescription = 4;</code>
       */
      public Builder clearProductDescription() {
        
        productDescription_ = getDefaultInstance().getProductDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string productDescription = 4;</code>
       */
      public Builder setProductDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productDescription_ = value;
        onChanged();
        return this;
      }

      private double productPrice_ ;
      /**
       * <code>double productPrice = 5;</code>
       */
      public double getProductPrice() {
        return productPrice_;
      }
      /**
       * <code>double productPrice = 5;</code>
       */
      public Builder setProductPrice(double value) {
        
        productPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double productPrice = 5;</code>
       */
      public Builder clearProductPrice() {
        
        productPrice_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.middleware.order.proto.OrderRequest)
    }

    // @@protoc_insertion_point(class_scope:com.middleware.order.proto.OrderRequest)
    private static final com.middleware.order.proto.Order.OrderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.middleware.order.proto.Order.OrderRequest();
    }

    public static com.middleware.order.proto.Order.OrderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRequest>
        PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
      public OrderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderRequest> getParserForType() {
      return PARSER;
    }

    public com.middleware.order.proto.Order.OrderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.middleware.order.proto.OrderResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.middleware.order.proto.OrderResponse}
   */
  public  static final class OrderResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.middleware.order.proto.OrderResponse)
      OrderResponseOrBuilder {
    // Use OrderResponse.newBuilder() to construct.
    private OrderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderResponse() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.middleware.order.proto.Order.OrderResponse.class, com.middleware.order.proto.Order.OrderResponse.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.middleware.order.proto.Order.OrderResponse)) {
        return super.equals(obj);
      }
      com.middleware.order.proto.Order.OrderResponse other = (com.middleware.order.proto.Order.OrderResponse) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.middleware.order.proto.Order.OrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.middleware.order.proto.Order.OrderResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.middleware.order.proto.OrderResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.middleware.order.proto.OrderResponse)
        com.middleware.order.proto.Order.OrderResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.middleware.order.proto.Order.OrderResponse.class, com.middleware.order.proto.Order.OrderResponse.Builder.class);
      }

      // Construct using com.middleware.order.proto.Order.OrderResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.middleware.order.proto.Order.internal_static_com_middleware_order_proto_OrderResponse_descriptor;
      }

      public com.middleware.order.proto.Order.OrderResponse getDefaultInstanceForType() {
        return com.middleware.order.proto.Order.OrderResponse.getDefaultInstance();
      }

      public com.middleware.order.proto.Order.OrderResponse build() {
        com.middleware.order.proto.Order.OrderResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.middleware.order.proto.Order.OrderResponse buildPartial() {
        com.middleware.order.proto.Order.OrderResponse result = new com.middleware.order.proto.Order.OrderResponse(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.middleware.order.proto.Order.OrderResponse) {
          return mergeFrom((com.middleware.order.proto.Order.OrderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.middleware.order.proto.Order.OrderResponse other) {
        if (other == com.middleware.order.proto.Order.OrderResponse.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.middleware.order.proto.Order.OrderResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.middleware.order.proto.Order.OrderResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.middleware.order.proto.OrderResponse)
    }

    // @@protoc_insertion_point(class_scope:com.middleware.order.proto.OrderResponse)
    private static final com.middleware.order.proto.Order.OrderResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.middleware.order.proto.Order.OrderResponse();
    }

    public static com.middleware.order.proto.Order.OrderResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderResponse>
        PARSER = new com.google.protobuf.AbstractParser<OrderResponse>() {
      public OrderResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderResponse> getParserForType() {
      return PARSER;
    }

    public com.middleware.order.proto.Order.OrderResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_middleware_order_proto_OrderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_middleware_order_proto_OrderRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_middleware_order_proto_OrderResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_middleware_order_proto_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Order.proto\022\032com.middleware.order.prot" +
      "o\"~\n\014OrderRequest\022\021\n\tproductId\030\001 \001(\005\022\023\n\013" +
      "productName\030\002 \001(\t\022\024\n\014productColor\030\003 \001(\t\022" +
      "\032\n\022productDescription\030\004 \001(\t\022\024\n\014productPr" +
      "ice\030\005 \001(\001\" \n\rOrderResponse\022\017\n\007message\030\001 " +
      "\001(\t2\325\001\n\014OrderService\022a\n\nplaceOrder\022(.com" +
      ".middleware.order.proto.OrderRequest\032).c" +
      "om.middleware.order.proto.OrderResponse\022" +
      "b\n\013updateOrder\022(.com.middleware.order.pr" +
      "oto.OrderRequest\032).com.middleware.order.",
      "proto.OrderResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_middleware_order_proto_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_middleware_order_proto_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_middleware_order_proto_OrderRequest_descriptor,
        new java.lang.String[] { "ProductId", "ProductName", "ProductColor", "ProductDescription", "ProductPrice", });
    internal_static_com_middleware_order_proto_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_middleware_order_proto_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_middleware_order_proto_OrderResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
